language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: KNBvBidsJJVFJ3giekgTnbKj/vXZimTmj/EGjoxhmOFxJmM1dQwT7Rmw8FBdx8i4l+Z7+yfNieQGaVGobmJHa2VDuFzCClkeJ78kDOBhZaKw3xaqlh//4FUKZE3RNmbVVZwtgAVcuO9kwew/b03e34X+ny+E8NmQX31zbJzn7knha1nXZBeWcu4cBbe3UQvSIo8cTy1PWFmJJN6XrpOwAiOhbkvpeYqHfzGfpVEgpekL4Gm812nfF3edmkvvjXIWRV/vOJs19c5dry26ULLZP6PlZrDf61UfQ6lEvgQl4bqwBn7lHTbt9v/W708AjyEvmLSONRcqjU9QQpgw/Z2IirSE+b8IpQ9s34JhcWUjR5OQRrBOvQjRgs7FrT+ibD4GaCEsZO7xwlbUKiDfhRAtcpygHWyoTOLBwybw+YmajLom27/Ji3DCNoEvJnHsQ7W9WwuDftZ/ToUCLlF6ztL87ORtMEiVHEseVr3aQoFdH/Xna766zTBpGWwPHRtKNhrxr751q2HoHPaESTExhdu+2TnrTsqrlDWm795I5lQnh6rVa9ekCuB0gLUzGnKH8e00PSJnl2GXrK6K6U0274VtiU+9hFAHyK9PWapOrGOvzODbua7LJvfmmRO8770iQQoaoVXqiyXr/ScMhuTJn2EX6pp1bPByhoZuGKwKh7ft070=
  app: turistmo
  on:
    repo: TuristMO/turistmo
addons:
  sonarcloud:
    organization: "turistmo-new"
    token:
      secure: "Dz9cX261ScQhePpJeslu3joStT5sGHLNeX6tdZ2T3JUEd3e3wfsyPtEyuvM1XAq+O0esDpSC6w7e054KioHPs8UmNaEOBoNOm6BnNs6llfz5nBNJG3whm4X9DPVSgtzfLbnSDdHskZNmeIU2/qYgAdzczBjAEQ1b+ntJZppeXs8wtYsUSRFmC7EwRwkgwcUZahvQIFw/X+sFCo4z8QSBoCg+M0l9zZLYZvCJCkDP39SiOHnGyXHfc5AAKOI3zEtj2rpXvpyC0yyfci7PbauD5oQH1ZEXp4bVu9dfn7YY9HKsHW3eHk4G0OSrwLluxXfiO5+EOE4cOazw4n/Oad1ONm9XvIjSMyoFKjOBELfheBTig2t9UQadk1SogPk6xpb7r00PU0Yo6rXZpMk/FXVYk8pLJKY9mopcp1gtEsBVqCdPcwWCBvVTEYnfNhWXAASEFBM9zv9CaJi+06leqB3IxYjx1IMQBriCiNNn5TWONZKiiqAuwxtgYdYEyvUYUZP9+yER9iUdLbTojKgjxz+WSiQvQ1qI9/dizNaplW6/v0w235+AC2RpFz1rXNUHNHvmxE73imF7twRy3ny7Y5cwMpdPmtTcwAfCdrbInRqpmrSOvmaXiXYN0U69XANgKleJReZnxKu1PqUbstFi6FSOLDhR/xEOOrEffYVDPLMVywc="
script:
  - chmod +x ./gradlew
  - "./gradlew clean build"
  - ./gradlew sonarqube
