language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: KNBvBidsJJVFJ3giekgTnbKj/vXZimTmj/EGjoxhmOFxJmM1dQwT7Rmw8FBdx8i4l+Z7+yfNieQGaVGobmJHa2VDuFzCClkeJ78kDOBhZaKw3xaqlh//4FUKZE3RNmbVVZwtgAVcuO9kwew/b03e34X+ny+E8NmQX31zbJzn7knha1nXZBeWcu4cBbe3UQvSIo8cTy1PWFmJJN6XrpOwAiOhbkvpeYqHfzGfpVEgpekL4Gm812nfF3edmkvvjXIWRV/vOJs19c5dry26ULLZP6PlZrDf61UfQ6lEvgQl4bqwBn7lHTbt9v/W708AjyEvmLSONRcqjU9QQpgw/Z2IirSE+b8IpQ9s34JhcWUjR5OQRrBOvQjRgs7FrT+ibD4GaCEsZO7xwlbUKiDfhRAtcpygHWyoTOLBwybw+YmajLom27/Ji3DCNoEvJnHsQ7W9WwuDftZ/ToUCLlF6ztL87ORtMEiVHEseVr3aQoFdH/Xna766zTBpGWwPHRtKNhrxr751q2HoHPaESTExhdu+2TnrTsqrlDWm795I5lQnh6rVa9ekCuB0gLUzGnKH8e00PSJnl2GXrK6K6U0274VtiU+9hFAHyK9PWapOrGOvzODbua7LJvfmmRO8770iQQoaoVXqiyXr/ScMhuTJn2EX6pp1bPByhoZuGKwKh7ft070=
  app: turistmo
  on:
    repo: TuristMO/turistmo
addons:
  sonarcloud:
    organization: TuristMO_turistmo-new
    token:
      secure: "******************"
env:
  global:
    secure: heZudF6rLWvogA2QW85IhI+8lHvtB9V21QEpWA0frmbdbRzWUfmkdjPhgq+jrQpLLiRBQ7T1Dol1WTTDygUMZh8CQon1l67Jbl04+7oLyL9cOSML8/jTRoDgcxCE4PMmNiCUTRCiwejMhlpkL9nOMV1aBjZl2mGYouRXfDP8xrzVQWohqxJ700guf29otEihdPOvy4P4K0D3p1HpGdIQB1ElPkJa4yySrr+4EohhIO070EM67ePDqTmXPqoJFDLAx2PBN7Jmt82c2iUrN64vw9qmTuk6i2FgvCAkkwWMy0J/8CS0Mem7fXSjd+gZYeMMhMG3YnE8Uebr9WnykcPPzn8/uHjQBwvaDGsUr7v0A5i/nH+HGljDAcw7xG2qabpbTQxHNSmVDIZD7l+h4tLqsaFy9F2f4g9aW8AgLn9KEcj3+8nI8An5nWnxawC77GzPxgNuMMvSrDFgBRpEds8vltrNlJDfv/AD+QYKjS3BERWxT7YHyj4m+pQnX4lDW5/EE09IamMKLAqrzXEoEMO503IjPHo4VNF8awfolQGQOHEgQt8PvpDnThOo6MRJ1zHb0L2M+to1bd4W0nA1WI70v3laL+eXuc2Dxjw/vpB291CcFUW1JrnR9ZIWTlrW0YFztn4jdcN5YW4Ku+imSLaPqcODiZax/RlT9a3Gg73Fui0=
script:
- "chmod +x ./gradlew"
- "./gradlew clean build"
- "./gradlew sonarqube"
