language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: KNBvBidsJJVFJ3giekgTnbKj/vXZimTmj/EGjoxhmOFxJmM1dQwT7Rmw8FBdx8i4l+Z7+yfNieQGaVGobmJHa2VDuFzCClkeJ78kDOBhZaKw3xaqlh//4FUKZE3RNmbVVZwtgAVcuO9kwew/b03e34X+ny+E8NmQX31zbJzn7knha1nXZBeWcu4cBbe3UQvSIo8cTy1PWFmJJN6XrpOwAiOhbkvpeYqHfzGfpVEgpekL4Gm812nfF3edmkvvjXIWRV/vOJs19c5dry26ULLZP6PlZrDf61UfQ6lEvgQl4bqwBn7lHTbt9v/W708AjyEvmLSONRcqjU9QQpgw/Z2IirSE+b8IpQ9s34JhcWUjR5OQRrBOvQjRgs7FrT+ibD4GaCEsZO7xwlbUKiDfhRAtcpygHWyoTOLBwybw+YmajLom27/Ji3DCNoEvJnHsQ7W9WwuDftZ/ToUCLlF6ztL87ORtMEiVHEseVr3aQoFdH/Xna766zTBpGWwPHRtKNhrxr751q2HoHPaESTExhdu+2TnrTsqrlDWm795I5lQnh6rVa9ekCuB0gLUzGnKH8e00PSJnl2GXrK6K6U0274VtiU+9hFAHyK9PWapOrGOvzODbua7LJvfmmRO8770iQQoaoVXqiyXr/ScMhuTJn2EX6pp1bPByhoZuGKwKh7ft070=
  app: turistmo
  on:
    repo: TuristMO/turistmo
addons:
  sonarcloud:
    organization: TuristMO_turistmo-new
    token:
      secure: "******************"
env:
  global:
    secure: dOPG6hITOGPF9XIpwFeq3BnUQxrEx1B74VBg2zNOGJpjx198mI+Y+J6xZyUQSC48UuuqVqVNE66zOaXNv1v8y9Z5aGWkjC0qKEh6WCnUWvmJ89hrqbRstTrwVHBw115BnZpqcXlqu+HZZuHbGdh4LZ+elCn3xCvXDQJtXcQRAXbjB4pdqs6zF2S7AlOBRhQq9YcfSxUTy1etK+gMf6Y4+rg1Hn+f6xQIYRLoYnt6qK6NvHbO21Yjbh3sT7QW5wDxqsb/NRGFl/mPrsNDN5EQrUu89sKTPsuUmkdIdYu/Caj8FmhEXp15CBYg1Jm7lka7vzyfpnBPY/z0psJ5leNC7TT7+Z61EvfAvwEf8928cpD+Oh3BAPQvR1UBW0T0DpwnZKOPqGb/DyCbxAciS6Zj+2EvNbCxRo8uKPUv/LKHU576JgEIyFAetW1RjRr6NnBQK4Jtanxswj7qJdA13LsgpR201lBopqEZbICVfUP3gHsjO47BwsNVeGVbfViFRqIO5m74oUOXl4JEIoGyaKNWwetkxmPSeWgr5ahR4U3yOky8Whei/T8+QbEDj4G1NTBSIkR/SfA7cZcHy+XhGhXvy6KDPZRNaz+QDlEQ2I7MN7emOnoE17NQdnl5ejL+oUyYoxh6RwhOHWlDZFdx1gVAJJI/bF9Z3hucuRdcteHK/sM=
script:
- "chmod +x ./gradlew"
- "./gradlew clean build"
- "./gradlew sonarqube"
