language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: KNBvBidsJJVFJ3giekgTnbKj/vXZimTmj/EGjoxhmOFxJmM1dQwT7Rmw8FBdx8i4l+Z7+yfNieQGaVGobmJHa2VDuFzCClkeJ78kDOBhZaKw3xaqlh//4FUKZE3RNmbVVZwtgAVcuO9kwew/b03e34X+ny+E8NmQX31zbJzn7knha1nXZBeWcu4cBbe3UQvSIo8cTy1PWFmJJN6XrpOwAiOhbkvpeYqHfzGfpVEgpekL4Gm812nfF3edmkvvjXIWRV/vOJs19c5dry26ULLZP6PlZrDf61UfQ6lEvgQl4bqwBn7lHTbt9v/W708AjyEvmLSONRcqjU9QQpgw/Z2IirSE+b8IpQ9s34JhcWUjR5OQRrBOvQjRgs7FrT+ibD4GaCEsZO7xwlbUKiDfhRAtcpygHWyoTOLBwybw+YmajLom27/Ji3DCNoEvJnHsQ7W9WwuDftZ/ToUCLlF6ztL87ORtMEiVHEseVr3aQoFdH/Xna766zTBpGWwPHRtKNhrxr751q2HoHPaESTExhdu+2TnrTsqrlDWm795I5lQnh6rVa9ekCuB0gLUzGnKH8e00PSJnl2GXrK6K6U0274VtiU+9hFAHyK9PWapOrGOvzODbua7LJvfmmRO8770iQQoaoVXqiyXr/ScMhuTJn2EX6pp1bPByhoZuGKwKh7ft070=
  app: turistmo
  on:
    repo: TuristMO/turistmo
addons:
  sonarcloud:
    organization: "turistmo"
    token:
      secure: "**************************"
4054095dfcd733d89e0a79ece9509010f5eaa558:
  secure: LTKxIUYyXMwE96R1RtCymh1c9O2y6PKzreH59VN3VL66eJwjS5gjKX7LUvUAGP1MnvZWsxXYwR7SsnXrzwG3HY3b6uQpxcxLmqr+IGFVsfi0U7Uh+2YC4inTrnhb0pQGLYmGtvk0DZTUKsFnr+Euf3f1IqMBZ1bomqs8L3OHfgCEw8u3L+lfyIjnnplu3Gax23SkYCJwO8JMw+eMEc0AjhRSfogsoDDpQbwVfETUTf9OSIwk1pSosy/aKPNL0SlNvBkCTe6zdVheCCq3WmmOcIsl1vHIQaYWgLBV558SKdqB9vHtDOSBqMfRJsEQv3vOJjsN2uiKb8u2z20B1glJYA0xhfONz/SxnyevaSabc3g/T9eh7C21KvmDdoqJu6Bf9n2049c2+lqC+xUCBX2M9IjozguLvgnuJhaVcWFOpT68pkW4m6WMofy42HgJXOb4jhr6KPu9godUngH4TBIkpN7jHsuPfMwecneMdYx0zu3uF6hRhZ/l941ZXR42TrIcgwnnRHLHf2tayAy6/jXaQg89K4yONsAd7EXMyanIGzlC4QfoJ3GBpR90FrzsnxIV6ccIT3HRAcsWlb9mBi6mvUAmkbBO2ZOYX6d2NMw7YmEet8tQi8Cl9XVUamULT0CXcavUifDs5QU2AS2k2TGM+ctu2SsWn8onvqa8MT72JgE=

script:
  - chmod +x ./gradlew
  - "./gradlew clean build"