language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: KNBvBidsJJVFJ3giekgTnbKj/vXZimTmj/EGjoxhmOFxJmM1dQwT7Rmw8FBdx8i4l+Z7+yfNieQGaVGobmJHa2VDuFzCClkeJ78kDOBhZaKw3xaqlh//4FUKZE3RNmbVVZwtgAVcuO9kwew/b03e34X+ny+E8NmQX31zbJzn7knha1nXZBeWcu4cBbe3UQvSIo8cTy1PWFmJJN6XrpOwAiOhbkvpeYqHfzGfpVEgpekL4Gm812nfF3edmkvvjXIWRV/vOJs19c5dry26ULLZP6PlZrDf61UfQ6lEvgQl4bqwBn7lHTbt9v/W708AjyEvmLSONRcqjU9QQpgw/Z2IirSE+b8IpQ9s34JhcWUjR5OQRrBOvQjRgs7FrT+ibD4GaCEsZO7xwlbUKiDfhRAtcpygHWyoTOLBwybw+YmajLom27/Ji3DCNoEvJnHsQ7W9WwuDftZ/ToUCLlF6ztL87ORtMEiVHEseVr3aQoFdH/Xna766zTBpGWwPHRtKNhrxr751q2HoHPaESTExhdu+2TnrTsqrlDWm795I5lQnh6rVa9ekCuB0gLUzGnKH8e00PSJnl2GXrK6K6U0274VtiU+9hFAHyK9PWapOrGOvzODbua7LJvfmmRO8770iQQoaoVXqiyXr/ScMhuTJn2EX6pp1bPByhoZuGKwKh7ft070=
  app: turistmo
  on:
    repo: TuristMO/turistmo
addons:
  sonarcloud:
    organization: TuristMO_turistmo-new
    token:
      secure: "******************"
script:
- chmod +x ./gradlew
- "./gradlew clean build"
- "./gradlew sonarqube"
dfea89823c0ee201263709a72c3e3f8426d2718d:
  secure: O+RkUGFpnkk80vBfTscAcokSw/rX9PDfr0uYVGc77GI8U/ZfhpW1ltHLhLZX+Rj8sOApEkWKyQzBMoypQu1X/yPB+exoslcZ0/SELakv6qvwZSVHAIgmbFMZpHQaYbSaTKzrN8fSYukVYh52+QNM8D9QrRZVgcJAwto198RzTPfDjQCui2Y4U7587DaJ87Qg1a2kseTgdJSoSzgUTgfSjSkSEZRDo+tHt0N4cAbs9szgoOFtLzYxfjCKTkN7a+LsnTJs4xhonvZS/9quamFfR9jSsRwQ0p7e7sBakMdgxo/5ywxnFS5NTmAQy4j76AeIvlH0Sw6sS7GlFTk7WPRQZf8FQSYZU8DGm7IGvnmnar/WidtyaMmn1xclak9HRGnUzfgBgqcrfI1WqPts1pwPAGxYoIaSZuR9oI+LRFrb28xNr7K1A8q6bkMSLU0tf1b38JfCiv7pSXreSmjcIO0ouw8izlL+d3VzJtljgBKIFz4d6J2kGd34VsDTU63LOm7f5rn+fMNCPUNpErPUmRbi8JTFb5vfPR5dM1eI6QCK7HjdR3I+z+7VHGh2skq2/0oG+QbeO8vd8IuAJSa2dH/56Y7WHVKkF+CvvsPBZrnsQJGKyoY/ALZ/I7YtdKXvlVBgD3Da22Fx+vijsg9E+MzvQWNPzIwxqSSJX9zgwNNlGaY=
