language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: KNBvBidsJJVFJ3giekgTnbKj/vXZimTmj/EGjoxhmOFxJmM1dQwT7Rmw8FBdx8i4l+Z7+yfNieQGaVGobmJHa2VDuFzCClkeJ78kDOBhZaKw3xaqlh//4FUKZE3RNmbVVZwtgAVcuO9kwew/b03e34X+ny+E8NmQX31zbJzn7knha1nXZBeWcu4cBbe3UQvSIo8cTy1PWFmJJN6XrpOwAiOhbkvpeYqHfzGfpVEgpekL4Gm812nfF3edmkvvjXIWRV/vOJs19c5dry26ULLZP6PlZrDf61UfQ6lEvgQl4bqwBn7lHTbt9v/W708AjyEvmLSONRcqjU9QQpgw/Z2IirSE+b8IpQ9s34JhcWUjR5OQRrBOvQjRgs7FrT+ibD4GaCEsZO7xwlbUKiDfhRAtcpygHWyoTOLBwybw+YmajLom27/Ji3DCNoEvJnHsQ7W9WwuDftZ/ToUCLlF6ztL87ORtMEiVHEseVr3aQoFdH/Xna766zTBpGWwPHRtKNhrxr751q2HoHPaESTExhdu+2TnrTsqrlDWm795I5lQnh6rVa9ekCuB0gLUzGnKH8e00PSJnl2GXrK6K6U0274VtiU+9hFAHyK9PWapOrGOvzODbua7LJvfmmRO8770iQQoaoVXqiyXr/ScMhuTJn2EX6pp1bPByhoZuGKwKh7ft070=
  app: turistmo
  on:
    repo: TuristMO/turistmo
addons:
  sonarcloud:
    organization: TuristMO_turistmo-new
    token:
      secure: "******************"
script:
- chmod +x ./gradlew
- "./gradlew clean build"
- "./gradlew sonarqube"
env:
  global:
    secure: hrR1Uvf5OPg3mbnrmFvQB7LqE7Jlt+lmyIxj/rsUlf33wBsVV6h8sOpsDFis3fqSR2LIXlpuoufw4iUoMLRUslR9YMMu3M/s07FYVHQEYB2jkqRns2rfIVMmQdBWIisimE2IE/LxRqVrqDr68aOMqQ69co24HNro6rqtwvCRJQ3YCAlbneAioi6QGpYvX0LiJLwpZu2zp4sKPpgfsBpI59QuGS9hJzeABBRsT8JfxRaQc4EEr5Ef9BmBdxWYeCGGR730b7UN0MHgyaS/rmoZQb3f0vyy/EaB3DqJpsrddjOK0qwcLo3tUQBPLcvI9XMKR42lWpcSgQm8L1HrWyXMxBXUbgxgFPnQNmxhtM/9P9b02NWpVQgc//D7PmQgTkGyeBURxEoHFpZumGR1L5o1BEaqn4cgnO9ieVmFGHZvJtnqPZIKRUh+sd0jTo4SROJ7p5ZkYmbW0YCx+FdENXQqueUa9Hab4LLmQBAvsApv5o1aBmxTbVl0mgTAYM7U3fpJjQ5l+fp1kxCQtjo77lvl1q4IxWyr2j2PR/MsiVw6TdbQZv/w2WFvzohoqHm3O48+wyDE8K4YuY10FvlveF4p2IOgH4D43g7gRriJgqeKWAUxj+R+ydqSMYT0GH9giDlT5rXybJSfKpbHpMbs5nvMiiqLHZ7s0OSbz794aVS+z6o=
